Repository openshift/oc-compliance, pull requests merged in 2021-03, with the labels that each got.

#8 Use conditions for e2e test
  tests/e2e/e2e_suite_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#11 Add code to deal with race in install plans
  tests/e2e/e2e_suite_test.go
  tests/e2e/helpers.go
Labels: approved

#10 Add e2e tests for rerun-now subcommand
  tests/e2e/helpers.go
  tests/e2e/rerunnow_test.go
Labels: approved, lgtm

#16 e2e: Add test case for `controls` subcommand
  tests/e2e/controls_test.go
Labels: approved

#17 Add e2e tests for view-result sub-command
  internal/viewresult/result.go
  tests/e2e/viewresult_test.go
Labels: approved

#18 Add e2e tests for fetch-fixes sub-command and fix command docs
  README.md
  cmd/fetchfixes.go
  tests/e2e/fetchfixes_test.go
Labels: approved

#19 Add dependabot configuration
  .github/dependabot.yml
Labels: approved

#26 minor typos fix in README.md
  README.md
Labels: approved, lgtm, ok-to-test

#27 Fix bind command help text
  cmd/bind.go
Labels: approved, lgtm

#29 More help text updates
  .gitignore
  cmd/bind.go
  cmd/controls.go
  cmd/fetchfixes.go
  cmd/fetchraw.go
  cmd/rerunnow.go
  cmd/viewresult.go
Labels: approved, lgtm

#31 Fix remaining instances of the JAORMX namespace
  Makefile
  cmd/bind.go
  cmd/controls.go
  cmd/fetchfixes.go
  cmd/fetchraw.go
  cmd/rerunnow.go
  cmd/viewresult.go
  go.mod
  internal/bind/context.go
  internal/controls/context.go
  internal/controls/profiles.go
  internal/fetchfixes/complianceremediations.go
  internal/fetchfixes/context.go
  internal/fetchfixes/profiles.go
  internal/fetchfixes/rules.go
  internal/fetchraw/compliancescans.go
  internal/fetchraw/compliancesuites.go
  internal/fetchraw/options.go
  internal/fetchraw/scansettingbindings.go
  internal/rerunnow/compliancescans.go
  internal/rerunnow/compliancesuites.go
  internal/rerunnow/context.go
  internal/rerunnow/scansettingbindings.go
  internal/viewresult/context.go
  internal/viewresult/result.go
Labels: approved, lgtm
